# Set up the Rust toolchain.
language: rust
rust:
- stable
- beta
- nightly

before_script:
- export PATH=$PATH:/home/travis/.cargo/bin

os:
- linux
- osx
- windows

branches:
  only:
  - master

script:
- cargo build
