[package]
name = "crossterm"
version = "0.1.0"
authors = ["T <timonpost@hotmail.nl>"]

[dependencies]
[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
kernel32-sys = "0.2.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"


