[package]
name = "crossterm"
version = "0.1.0"
authors = ["T <timonpost@hotmail.nl>"]

[dependencies]
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winbase","winuser","consoleapi","processenv","wincon", "handleapi"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"



