name: Crossterm Test

on:
  # Build master only
  push:
    branches:
      - master
  # Build pull requests targeting master branch only
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Running on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019, macOS-latest]
        rust: [stable, nightly]
        include:
          - rust: stable
            can-fail: false
          - rust: nightly
            can-fail: true
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
        with:
          fetch-depth: 1
    - name: Install Rust
      uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
        components: rustfmt
      continue-on-error: ${{ matrix.can-fail }}
    - name: Toolchain Information
      run: |
        rustc --version
        rustfmt --version
        rustup --version
        cargo --version
      continue-on-error: ${{ matrix.can-fail }}
    - name: Check Formatting
      if: matrix.rust == 'stable'
      run: cargo fmt --all -- --check
      continue-on-error: ${{ matrix.can-fail }}
    - name: Test Build
      run: cargo build
      continue-on-error: ${{ matrix.can-fail }}
    - name: Run Tests
      run: cargo test --all-features -- --nocapture --test-threads 1
      continue-on-error: ${{ matrix.can-fail }}
